# Generated by Django 4.2.2 on 2023-06-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_child_age_alter_child_child_mpid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
