# Generated by Django 4.0.4 on 2023-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_vaccinationrecord_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='date_administered',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
