# Generated by Django 4.2.2 on 2023-06-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_vaccinationrecord_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='child_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.child'),
        ),
    ]
