# Generated by Django 4.2.2 on 2023-06-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_vaccinationrecord_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.child'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='date_administered',
            field=models.CharField(max_length=255),
        ),
    ]
