# Generated by Django 4.0.4 on 2023-06-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_vaccinationrecord_date_administered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vaccine'),
        ),
    ]
