# Generated by Django 4.0.4 on 2023-06-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_vaccinationrecord_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='child_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.child'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='date_administered',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.vaccine'),
        ),
    ]
